from pms.admin.tender import *
from pms.admin.attendence import *
from pms.admin.project import *
from pms.admin.machineries import *
from pms.admin.manpower import *
from pms.admin.pre_execution import *
from pms.admin.external_user import *
from pms.admin.requisition import *
from pms.admin.approval_permission import *
from pms.admin.tour_and_travel import *
from pms.admin.daily_expence import *
from pms.admin.accounts import *
from pms.admin.site_bills_invoices import *
from pms.admin.contractors import *
from pms.admin.batching_plant import *
