from pms.views.external_user import *
from pms.views.tender import *
from pms.views.attendence import *
from pms.views.project import *
from pms.views.machineries import *
from pms.views.manpower import *
from pms.views.pre_execution import *
from pms.views.requisition import *
from pms.views.approval_permission import *
from pms.views.tour_and_travel import *
from pms.views.daily_expence import *
from pms.views.accounts import *
from pms.views.daily_worksheet import *
from pms.views.batching_plant import *
from pms.views.site_bills_invoices import *
from pms.views.contractors import *
