"""
Django settings for SSIL_SSO_MS project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# =============== ENV ===================
#import environ
#root = environ.Path(__file__) - 3 # three folder back (/a/b/c/ - 3 = /)
#env = environ.Env(DEBUG=(bool, False),) # set default values and casting
#environ.Env.read_env('.env') # reading .env file.
# environ.Env.read_env() 
# =============== ENV ===================

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'rd6)f1_h7@*ay@86e@)n(d#yfp8y$fsih1d_n9(*z73!9-awhb'
# print('SECRET_KEY: ', env('SECRET_KEY'))
#SECRET_KEY = env('SECRET_KEY')
SECRET_KEY='rd6)f1_h7@*ay@86e@)n(d#yfp8y$fsih1d_n9(*z73!9-awhb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',    
    'users',
    'core',
    'master',
    'rest_framework',
    'corsheaders',
    'mailsend',
    'smssend',
    'pms',
    'holidays',
    'drf_yasg',
    'vms',
    'etask',
    'tickettool',  
    'hrms',
    'attendance',
    'appversion',
    'eticket',
    'sslserver',
    # 'django_cron',
    'django_crontab',
    'django_celery_results',
    'knox',
    'notification',
    'channels',
    'crm',
    'vendor',
    'sscrm',
    'tdms'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'automated_logging.middleware.AutomatedLoggingMiddleware',
]

'''
     CRON SETTINGS & DECLARE ::
     --------------------------
     1) Attendance pending mail in every friday on a week (my_attendence_pending_mail_on_every_week)
     2) Final Attendance pending mail before going to lock attendance (my_attendence_mail_before_lock_job)
     3) Update attendance lock status once in a month (my_attendence_lock_job)
'''
CRONJOBS = [
   # ('35 13 * * *', 'SSIL_SSO_MS.cron.my_attendence_mail_before_lock_job','>> /var/www/html/ssilmanagement/ssil_sso_ms/mail_job.log'),
   #('10 18 * * *', 'SSIL_SSO_MS.cron.my_attendence_lock_job','>> /var/www/html/ssilmanagement/ssil_sso_ms/scheduled_job.log'),
   #('55 15 * * *', 'SSIL_SSO_MS.cron.my_attendence_mail_before_lock_job','>> /var/www/html/ssilmanagement/ssil_sso_ms/mail_job.log'),
   #('0 18 * * TUE', 'SSIL_SSO_MS.cron.my_attendence_pending_mail_on_every_week','>> /var/www/html/ssilmanagement/ssil_sso_ms/mail_job.log'),
   ('0 6 * * FRI', 'SSIL_SSO_MS.cron.my_attendence_pending_mail_on_every_friday_in_a_week','>> /var/www/html/ssilmanagement/ssil_sso_ms/mail_job.log'),
]



ROOT_URLCONF = 'SSIL_SSO_MS.urls'
CORS_ORIGIN_ALLOW_ALL = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SSIL_SSO_MS.wsgi.application'

# ASGI

ASGI_APPLICATION = 'SSIL_SSO_MS.routing.application'

SWAGGER_SETTINGS = {
   'SECURITY_DEFINITIONS': {
      'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
      }
   }
}
REDOC_SETTINGS = {
   'LAZY_RENDERING': True,
}

'''
     DATABASE SETTINGS & DECLARE
'''

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sas',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'sql_mode': 'traditional',
        }
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = ('backends.CaseInsensitiveModelBackend', )

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE =  'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

# USE_TZ = False


STATIC_URL = '/static/'



# ============================ Oauth implementation =====================================#
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (  # added
        'knox.auth.TokenAuthentication',
    ),
    'DATETIME_FORMAT': "%m/%d/%Y %H:%M:%S",
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     'rest_framework.authentication.TokenAuthentication',
    # ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    ),
   # 'EXCEPTION_HANDLER':'exceptions.root_simple_error_handler'
}
# ============================ Oauth implementation =====================================#



STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_ROOT_EXPORT = os.path.join(BASE_DIR, "")
SERVER_URL = 'http://127.0.0.1:8000/'

#######
MSG_SUCCESS="Success"
MSG_NO_DATA="No Data Found"
MSG_ERROR="Failure"


'''
    ALL SMTP & MAIL SETTINGS 
'''
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_FROM_C = 'support@info.com'
DEFAULT_FROM_EMAIL = 'support@info.com'




######### TEXT LOCAL SMS GATEWAY CONFIGURATION ########

TXT_LOCAL_SMS_API_KEY = "sd"


# ============= Error Msg configrations =================
MSG_SUCCESS="Success"
MSG_NO_DATA="No Data Found"
MSG_ERROR="Failure"
# ============= Error Msg configrations =================


# A sample logging configuration. The only tangible logging
# performed by this configuration is to send an email to
# the site admins on every HTTP 500 error when DEBUG=False.
# See http://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
from os.path import abspath, basename, dirname, join, normpath

DJANGO_ROOT = dirname(dirname(abspath(__file__)))

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
#             'datefmt' : "%d/%b/%Y %H:%M:%S"
#         },
#         'simple': {
#             'format': '%(levelname)s %(message)s'
#         },
#     },  
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.handlers.TimedRotatingFileHandler',
#             'filename': os.path.join(DJANGO_ROOT, 'debug.log'),
#             'when': 'D', # this specifies the interval
#             'interval': 1, # defaults to 1, only necessary for other values 
#             'backupCount': 1, # how many backup file to keep, 5 days
#             'formatter': 'verbose',
#         },

#     },  
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'level': os.getenv('DJANGO_LOG_LEVEL', 'DEBUG'),
#         },
#         '': {
#             'handlers': ['file'],
#             'level': os.getenv('DJANGO_LOG_LEVEL', 'DEBUG'),
#         }
#     },  
# }

'''
    For cellery
'''
CELERY_BROKER_URL = 'redis://127.0.0.1:6379' 
CELERY_RESULT_BACKEND = 'django-db' 
CELERY_CACHE_BACKEND = 'django-cache' 
CELERY_ACCEPT_CONTENT = ['application/json'] 
CELERY_TASK_SERIALIZER = 'json' 
CELERY_RESULT_SERIALIZER = 'json'


'''
    For KNOX 
'''
from datetime import timedelta
from rest_framework.settings import api_settings
REST_KNOX = {
  'SECURE_HASH_ALGORITHM': 'cryptography.hazmat.primitives.hashes.SHA512',
  'AUTH_TOKEN_CHARACTER_LENGTH': 64,
  'TOKEN_TTL': None, # timedelta(hours=10) Token never expire
  'USER_SERIALIZER': 'knox.serializers.UserSerializer',
  'TOKEN_LIMIT_PER_USER': None,
  'AUTO_REFRESH': False,
  #'EXPIRY_DATETIME_FORMAT': api_settings.DATETME_FORMAT,
}
